handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose
    level: DEBUG
    stream: ext://sys.stdout

loggers:
  pyads:
    level: DEBUG
    handlers:
      - console
    propagate: no

  root:
    level: DEBUG
    handlers:
      - console
