handlers:
  pyads.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/pyads.debug.log
    maxBytes: 10_000_000
    backupCount: 7
    
  ads_client.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/ads_client.debug.log
    maxBytes: 10_000_000
    backupCount: 7

loggers:
  pyads:
    level: DEBUG
    handlers:
      - pyads.debug.file

  ads_client:
    level: DEBUG
    handlers:
      - ads_client.debug.file
    propagate: false

  root:
    level: DEBUG
    handlers:
      - console
    

